language: perl
perl:
  - "5.6"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    # FIXME Later revisions fail to install 5.6 :-S
  - (cd ~/travis-perl-helpers && git checkout d55205f)
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpan-install --deps
